version: '2.0'

services:
    info-screen:
        container_name: info-screen
        build:
            context: ./
        volumes:
            - ./public/cdn:/usr/src/app/public/cdn
        ports:
            - '5000:80'
            - '5001:81'
        env_file:
            - ./.env.production
